# Generated by Django 3.0.6 on 2020-05-20 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Choice'),
        ),
    ]
